### ISSUE TITLE
Response Content Lost

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#100]
Not all the information inputted by the person submitting the form is being saved.

**Comment by CarlSteven** [comment]
Could you please provide a example form? Also, what is being lost?

**Comment by hejalsoni** [comment]
If you go into the Freshman Application form, the NAME block, all of the APPLICATION block, all of the HIGH SCHOOL INFORMATION block do not get saved.
In the Summer Undergraduate Research Fellowship Application Form, the NAME block isn't being saved.

**Comment by hejalsoni** [comment]
I tried to inspect the element like you showed me how to on the application and the response page, but it is not giving me anything...

**Comment by CarlSteven** [comment]
What exactly do you mean by do not get saved?
- Responses don't appear in the responses tab?
- You can't make edits to the form?

**Comment by hejalsoni** [comment]
Responses don't appear in the responses tab

**Comment by CarlSteven** [comment]
Known issue with backend! @tabrown3 and I will upload a new version in a few minutes. You may experience downtime.

**Comment by hejalsoni** [comment]
Woot! Thank you!

**Comment by CarlSteven** [comment]
Should be fixed. Please give it a test.

If any problems persist, reopen this issue.

**Comment by hejalsoni** [comment]
It still does not work on the Summer Undergraduate Research Fellowship Application Form.

**Comment by CarlSteven** [comment]
But it does work on the Freshman Application form?

**Comment by hejalsoni** [comment]
No it does not.

**Comment by hejalsoni** [comment]
It works in Summer Undergraduate Research Fellowship Application Form, but not in the Freshman Application
