### ISSUE TITLE
Inconsistencies in the Save/Close option

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#106]
When you are creating a form, different blocks have different options. Some of them have a "Save" button instead of a "Close" button. It would be nice if this was consistent. There are images below that would clearly define what I am talking about.

It's the blue button next to the white and red ones.

![screen shot 2015-03-02 at 3 21 39 pm](https://cloud.githubusercontent.com/assets/10925312/6450809/142fd478-c0f0-11e4-835d-a0eddb2562c6.png)

![screen shot 2015-03-02 at 3 22 01 pm](https://cloud.githubusercontent.com/assets/10925312/6450812/182b62c2-c0f0-11e4-96c9-8b6307dc65e5.png)

**Comment by CarlSteven** [comment]
Closed in #96. Not yet pushed to test environment. My mistake for closing it before push/merge into master.
