### ISSUE TITLE
Custom File Upload Type

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#107]
A component needs to be added in the upload file block that tells the user that they can only upload PDFs and Word documents. Currently, it only allows the user to upload PDFs and Word documents.

**Comment by CarlSteven** [comment]
Temporary Fix:
![image](https://cloud.githubusercontent.com/assets/7702743/6479510/10a20412-c20c-11e4-9cd8-adf1eb66b5bb.png)

Custom File Upload Type is pending
