### ISSUE TITLE
Buttons Are Appearing on Two Lines

### ISSUE THREAD

**Issue by CarlSteven** [DataAnalyticsinStudentHands/FormBuilder#108]
![image](https://cloud.githubusercontent.com/assets/7702743/6471152/550c4c9c-c1ae-11e4-91f9-bcb89b2486f2.png)

**Comment by CarlSteven** [comment]
![image](https://cloud.githubusercontent.com/assets/7702743/6471170/841de3f6-c1ae-11e4-829c-4e776e990911.png)
![image](https://cloud.githubusercontent.com/assets/7702743/6471173/8a213abe-c1ae-11e4-8f28-fdcf3637993e.png)

Better screenshots with more context.

Also:
Here you can also see that the 'required' checkbox is sort of unbalanced too. Here's a reference screenshot of how it used to be.
![image](https://cloud.githubusercontent.com/assets/7702743/6471219/c7c41a12-c1ae-11e4-9b47-74348466427c.png)

**Comment by vnguyen9** [comment]
You want to make them align?
My branch looks good though 
Let me see

**Comment by vnguyen9** [comment]
Done
