### ISSUE TITLE
Confirmation for deleting a text block.

### ISSUE THREAD

**Issue by srirampotluri** [DataAnalyticsinStudentHands/FormBuilder#110]
For deleting the text block, it doesn't ask for any confirmation.
It directly deletes the text block without any prompting.

![screen shot 2015-03-03 at 4 00 55 pm](https://cloud.githubusercontent.com/assets/8973449/6473395/b11674ee-c1be-11e4-9153-ffb24404cd58.png)

**Comment by tabrown3** [comment]
Related to Deleting Questions, #91.
