### ISSUE TITLE
State block in the PDF still shows only 2 letters

### ISSUE THREAD

**Issue by srirampotluri** [DataAnalyticsinStudentHands/FormBuilder#113]
While filling out the application, the state block shows the whole state name.(TEXAS)

![screen shot 2015-03-04 at 12 31 43 pm](https://cloud.githubusercontent.com/assets/8973449/6490244/7c7136be-c26a-11e4-9a1d-4bfd298fe518.png)

But after submitting, in the PDF file, it still shows only 2 characters(TX)
![screen shot 2015-03-04 at 12 33 37 pm](https://cloud.githubusercontent.com/assets/8973449/6490278/baf5a7c6-c26a-11e4-9deb-a2a46ce3d276.png)

**Comment by CarlSteven** [comment]
I think is works as intended since most address blocks usually go for the two letter state and it's easier to read. However, users get to pick the entire state name.

It's easily changeable if really required. I'm not sure which is the best.

**Comment by srirampotluri** [comment]
What you said is true. Almost all the applications go with only "Two Letters" in the state block.
I pointed it out because its different in the form and the response PDF
I would go with the Two Letter format.
