### ISSUE TITLE
Cannot upload files in Yosemite Firefox

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#121]
If you open up the Yosemite Firefox test, the responses page shows that no files were uploaded. I know I uploaded the files needed.
![screen shot 2015-03-30 at 9 15 21 am](https://cloud.githubusercontent.com/assets/10925312/6898147/e838e40c-d6bd-11e4-9088-fabe2487557a.png)

**Comment by CarlSteven** [comment]
Note: File upload fails in all browsers due to backend issue.

**Comment by CarlSteven** [comment]
Should be fixed now.
