### ISSUE TITLE
[Yosemite Firefox] Files are not being uploaded

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#127]
Files are not being uploaded.

**Comment by CarlSteven** [comment]
Hm... it shows up for me...
![image](https://cloud.githubusercontent.com/assets/7702743/6925426/d6d71584-d7a4-11e4-9016-d8d8b608859c.png)

**Comment by CarlSteven** [comment]
Please reopen if problem persists. I have tested on both FireFox Windows + Yosemite.

**Comment by hejalsoni** [comment]
If you go to the responses page, there is no file. It says that when you
upload it but it doesn't save.

On Tuesday, March 31, 2015, CarlSteven notifications@github.com wrote:

> Please reopen if problem persists. I have tested on both FireFox Windows +
> Yosemite.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DataAnalyticsinStudentHands/FormBuilder/issues/127#issuecomment-88188462
> .

## 

Hejal Soni
Student | Nutrition | College of Liberal Arts and Social Sciences
Residential Advisor | Cougar Village 2 | University of Houston

**Comment by CarlSteven** [comment]
Have you tested again today? I believe I updated the backend and tested it which seemed to fix the issue.

**Comment by hejalsoni** [comment]
I will try it today!

Hejal Soni
Student | Nutrition | College of Liberal Arts and Social Sciences
Residential Advisor | Cougar Village 2 | University of Houston
