### ISSUE TITLE
Studies UI: Fixed Times, Delete Participants, Delete Studies

### ISSUE THREAD

**Issue by cmholley** [DataAnalyticsinStudentHands/FormBuilder#131]
The fixed times interface should not have dates, only times, not date and times. No way to remove participants. No way to remove studies.

**Comment by CarlSteven** [comment]
Re: fixedTimes -> How is this stored in DB? Right now that table seems empty...

Haven't tested with 100% accuracy, but it seems like they aren't being persisted to DB since I don't get them when I retrieve.

**Comment by CarlSteven** [comment]
Also, getting 500 from server when I try to add new participants. ... Old participants work fine.

**Comment by CarlSteven** [comment]
Closing since @cmholley said that these issues are not present in latest version of backend.
