### ISSUE TITLE
Cannot login to FormBuilder

### ISSUE THREAD

**Issue by vnguyen9** [DataAnalyticsinStudentHands/FormBuilder#139]
Mac Os 10.10.5
Chrome Version 45.0.2454.85 (64-bit)

![screen shot 2015-09-02 at 3 21 11 pm](https://cloud.githubusercontent.com/assets/6502307/9643235/5b2ed640-5186-11e5-8258-d71c69bfacbc.png)
![screen shot 2015-09-02 at 3 21 10 pm](https://cloud.githubusercontent.com/assets/6502307/9643238/5e7cf2aa-5186-11e5-91c1-6ac025c8675f.png)

**Comment by CarlSteven** [comment]
This may be due to a misconfig of our SSL according to https://www.chromium.org/administrators/err_ssl_weak_server_ephemeral_dh_key

This flag was introduced in Chrome 45 which is why I am not seeing this error as I'm still on Chrome 44.

**Comment by vnguyen9** [comment]
So what do we have to do?

Change to ECDHE?

**Comment by CarlSteven** [comment]
Should be fixed now.
