### ISSUE TITLE
Permission Control

### ISSUE THREAD

**Issue by peggylind** [DataAnalyticsinStudentHands/FormBuilder#16]

**Comment by CarlSteven** [comment]
This is sharing forms with users based on e-mail.
1. User A could enter User B's e-mail (username) and User B would get access to the form and get a e-mail.
2. [stretch goal] If User B is not a user, then send User B an invitation to register?

**Comment by Tswiggs** [comment]
Can we lay out the permission levels real quick? My assumptions:

Role A: has read, write and delete permissions for the form and can read responses to that form
Role B: has read permissions for both the form and responses to it

BTW this implementations wouldnt require defining new permission levels as long as we double check the authorization statements to make sure we are using read, write delete appropriately.

When when a user creates a form they are currently Role A.  If the creator shares the form they could give the other user Role A or B.  

Big question, How do you want to handle email notifications?  Do we need to a new table to track notification subscriptions?

**Comment by CarlSteven** [comment]
I was thinking on the back of my mind that it could look something like:
- owner (all)
- collaborator(all, but delete)
- viewer (no edit, but read responses)
- responder (simply submit responses)

Names for these roles are probably not right.

**Comment by Tswiggs** [comment]
Thats fine, I just talked to peggy and it looks like we are just going to expose checkboxes for R/W/D for the form and the responses to the form.  This also involves implementing the reverse lookup where you can see all users who have a given permission on an object, it has to be done now.

**Comment by CarlSteven** [comment]
Gotcha. Any idea how this works with forms that only certain people are able to fill out?

Should we split that ‘R’ permission to ‘Respond’ and ‘Read Responses’ or something?

**Comment by CarlSteven** [comment]
@Tswiggs what happened to this?

**Comment by CarlSteven** [comment]
Goals for Thursday (4/17):
- Somewhat ready backend ready to test
- Frontend: Have a GUI for Permission Control ready to connect to backend

**Comment by cmholley** [comment]
Finished in feature/permissions branch, the merged into the feature/studies branch.
