### ISSUE TITLE
Box deletion

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#34]
When I try to delete one box, it deletes the boxes below it, but not the boxes above it.

**Comment by CarlSteven** [comment]
I think this is a duplicate of #2

Does the problem go away when you refresh the page after entering the form builder/editor?

**Comment by hejalsoni** [comment]
It works now!

**Comment by CarlSteven** [comment]
Thanks! That definitely means it's caused by #2 please continue tracking the issue there.
