### ISSUE TITLE
Register screen has inconsistencies

### ISSUE THREAD

**Issue by peggylind** [DataAnalyticsinStudentHands/FormBuilder#38]
The Register page has a "Sign in" button, but what it does it sends the registration information to the server and then sends to user back to the sign-in screen. The button should be "Register" or let the user sign-in with the newly generated credentials.

Also, on the login page it reads "Email address" to login, the registration page however asks for a "username"

Why are we collecting First Name, Last Name during registration?

![screen shot 2015-02-09 at 4 39 27 pm](https://cloud.githubusercontent.com/assets/6371988/6117462/4d594ff8-b07a-11e4-901e-76a157185886.png)

**Comment by CarlSteven** [comment]
I'm in the middle of fixing that confusing username field and button, haven't committed it yet.

There's no real reason to collect first/last name and they're not required fields. Should I remove them altogether?
