### ISSUE TITLE
Private vs. Public (do you need to log in to respond to a form)

### ISSUE THREAD

**Issue by peggylind** [DataAnalyticsinStudentHands/FormBuilder#4]

**Comment by CarlSteven** [comment]
Form Settings requirement. Need field to store this.

A server-side filter on this would be necessary so that ROLE_VISITOR are not able to pull down the form and only ROLE_USER and higher can retrieve it. GETs should fail with a pre-defined 5xx error code so we can handle it properly client-side.

**Comment by Tswiggs** [comment]
This was also implemented last week.  Is in the current war.

**Comment by CarlSteven** [comment]
I get a 500 - Access is denied unless form is public and open.

**Comment by CarlSteven** [comment]
I had to update the war with the new 401/filtered object stuff, that's what fixed it. Implemented client-side. Same thing for #5
