### ISSUE TITLE
filename for download pdf

### ISSUE THREAD

**Issue by DrDanPrice** [DataAnalyticsinStudentHands/FormBuilder#41]
For csv, it's filename_responses.csv
For pdf, it's just file.pdf

Should be the same. My vote is that it has date-time in the title, not "responses".
title_date.time? Not sure what's best way? Underscore or period?

**Comment by CarlSteven** [comment]
What's the best way to format the timestamp?
FORM_NAME_02102015_144536.csv
or
FORM_NAME_02102015_024308PM.csv
or almost anything else, really.

**Comment by CarlSteven** [comment]
Current format is: FORM_NAME_02102015_144536.csv. This is changeable if necessary.
