### ISSUE TITLE
Login discrepancies

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#44]
Somehow there are two different accounts set up. If I log in using my username, I can access a different account then when I log in using my email address. Formbuilder accepts my password both times though.

**Comment by CarlSteven** [comment]
You have two accounts, most likely from registering twice?

**Comment by hejalsoni** [comment]
I did not believe I registered twice. Is there anyway to check?

**Comment by CarlSteven** [comment]
I checked and you have two accounts: one under username and one under e-mail address.

This is most likely the cause.

**Comment by hejalsoni** [comment]
Okay! Sorry about that! We would need to prevent other users from creating the same problem. Would a proper solution be to clarify whether we want a username or email address in the registration box? When I login, it asks me for my email address, but the registration box asks me for a username. It's confusing.

**Comment by CarlSteven** [comment]
This is fixed as of #38, pending push to testing URL. You should see it live later today.
