### ISSUE TITLE
Navigation and UI Issues

### ISSUE THREAD

**Issue by cmholley** [DataAnalyticsinStudentHands/FormBuilder#45]
There are some simple UI changes regarding navigation.

After response is filled out, buttons to return to other pages. 
Go from form Settings to form builder (When you are editing a form and go to settings, you have to go back to the beginning to the home in order to get back to the form, and changes can't be saved)

Display username next to log out

**Comment by CarlSteven** [comment]
**Addressed:**
- Adds Settings -> Builder Button
- Adds Username by LogOut

**Not Addressed:**
After response is filled out, buttons to return to other pages. Instead added a close window/tab button to the finish page.

If a user is not logged in (public form) it does them no good to go to other parts of the webapp. We will add additional navigation once #4 is done and we have private (login-only) forms and more user-response based tracking.
