### ISSUE TITLE
Form Names on Responses and Organization

### ISSUE THREAD

**Issue by cmholley** [DataAnalyticsinStudentHands/FormBuilder#46]
When in the responses window, you can't see the name of the form responses, just the number. 
There is also not much organization for the responses, it just presents them in the order they were filled out.

**Comment by CarlSteven** [comment]
We had some questions about this the last time it came up:
- What is the "name" of the response? What if there is no "name" question? Should we give a way for users to pick what question is the "name"?
- How do we want the responses to be sorted? What criteria? Perhaps multi-column format?

**Comment by CarlSteven** [comment]
We will move towards a multi-column tabular format that supports searching by column header.
