### ISSUE TITLE
Able to change answers in reponses

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#47]
It allows changes to be made to the responses. After responses are stored, they can be edited in the textboxes. I have the steps of how to be able to locate where the problem is in in the images below. They are in order.

![problem 1](https://cloud.githubusercontent.com/assets/10925312/6151644/d11f8a06-b1dc-11e4-80ac-7858994fa282.png)
![problem 2](https://cloud.githubusercontent.com/assets/10925312/6151649/d4f85ee6-b1dc-11e4-85a0-0ad5ab8a2299.png)
![problem 3](https://cloud.githubusercontent.com/assets/10925312/6151652/d8a369dc-b1dc-11e4-8835-37ab77740421.png)
![problem 4](https://cloud.githubusercontent.com/assets/10925312/6151656/dc19f1a8-b1dc-11e4-9c16-d0b7a8110f9c.png)
![problem 5](https://cloud.githubusercontent.com/assets/10925312/6151657/dfb2ca60-b1dc-11e4-995e-cfe6dcce32bd.png)

.

**Comment by CarlSteven** [comment]
Superseded by actions in #46
