### ISSUE TITLE
Response entry duplication

### ISSUE THREAD

**Issue by CarlSteven** [DataAnalyticsinStudentHands/FormBuilder#49]
I have a suspicion that #29 still exists for response_entries:

![image](https://cloud.githubusercontent.com/assets/7702743/6193388/6f2de7e8-b380-11e4-8911-eb19e78cac9b.png)

Not fully tested to be happening, but we have duplication of response_entries in the tables. Does not seem to affect frontend due to unique filtering, but it still seems to be there.

**Comment by cmholley** [comment]
Fixed. There was another .flush() call at the DAO layer.
