### ISSUE TITLE
Enable vs Disable (allows the form's creator to make the form unavailable without deleting)

### ISSUE THREAD

**Issue by peggylind** [DataAnalyticsinStudentHands/FormBuilder#5]

**Comment by CarlSteven** [comment]
Form Settings requirement. Need field to store this.

A server-side filter on this would be necessary so that users are not able to pull down the form and only the owner/collaborators can work with it. GETs should fail with a pre-defined 5xx error code so we can handle it properly client-side.

**Comment by Tswiggs** [comment]
I implemented this last week. Its in the current war

**Comment by CarlSteven** [comment]
I get a 500 - Access is denied unless form is public and open.
