### ISSUE TITLE
Can't see responses in Chrome for Windows

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#52]
On Windows, in Chrome, you cannot see the responses. You can see the responses on the Excel file and on the PDF, but not when you click "View".

**Comment by CarlSteven** [comment]
Fixed in https://github.com/DataAnalyticsinStudentHands/FormBuilder/commit/7a0c1ee5d83446248f619ba118f908c042256695

This corrupted question.options field in the backend by santizing string/quotation marks to death. Should not happen again.
