### ISSUE TITLE
Nothing happens if click certain part of the block

### ISSUE THREAD

**Issue by vnguyen9** [DataAnalyticsinStudentHands/FormBuilder#53]
Drag and drop maybe confusing to some people: it took me about 2 minutes to figure out.
![screen shot 2015-02-16 at 8 51 50 am](https://cloud.githubusercontent.com/assets/6502307/6213863/b2344010-b5b9-11e4-9e8f-9b7394af9a88.png)
![screen shot 2015-02-16 at 8 52 00 am](https://cloud.githubusercontent.com/assets/6502307/6213864/b4930832-b5b9-11e4-950b-3df202604180.png)
Add **ADD** and **REMOVE** **buttons**?

**Comment by CarlSteven** [comment]
Lets keep the drag+drop UI and move towards having the independent scrolling columns as in #54.
