### ISSUE TITLE
Independent scrolling column for building form

### ISSUE THREAD

**Issue by CarlSteven** [DataAnalyticsinStudentHands/FormBuilder#54]

**Comment by CarlSteven** [comment]
@nqv1994 I think this is done, but please take one last look at it.

**Comment by CarlSteven** [comment]
@nqv1994 I've merged in your commit to feature/design and tweaked the scroll values a tiny bit to ensure that it will meet top/bottom of page height within header bounds without any gap.

Tested and working on my end. This will close when we merge into master.

**Comment by vnguyen9** [comment]
I’m still trying to fixing the positioning issue of the left column. 
"position: absolute ignores other elements, apart from it’s position: relative ancestor."

**Comment by CarlSteven** [comment]
Huh, weird, I don't see any issue with the left column on my computer.

**Comment by vnguyen9** [comment]
it’s not perfectly aligned yet.

But it works though.
