### ISSUE TITLE
Date Field/Text Input/Checkbox/Multiselect/Radio/TextArea

### ISSUE THREAD

**Issue by peggylind** [DataAnalyticsinStudentHands/FormBuilder#6]

**Comment by CarlSteven** [comment]
Date Field: Yes - Perhaps add time field...
Text Input: Yes
Checkbox: Yes
Multiselect: Same as checkbox?
Radio: Yes
TextArea: Yes

**Comment by CarlSteven** [comment]
Closing under assumption multi-select is a checkbox.
