### ISSUE TITLE
Formbuilder does not save more than a certain amount of blocks

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#70]
It only let me save a certain amount of blocks. I could not save all of the form.

**Comment by cmholley** [comment]
How many blocks? Is this during creation or during response?

**Comment by hejalsoni** [comment]
It only saves the first seven blocks. This is during creation. It will not save anything even though I click save.

I tried putting a block in the middle to see if it would change anything, but I think it's not saving at all.

**Comment by CarlSteven** [comment]
Just tested working with about 15 blocks during creation. What browser/OS?

**Comment by hejalsoni** [comment]
Chrome; MAC Yosemite

**Comment by CarlSteven** [comment]
Unable to reproduce, do you get any errors in the console? On screen?

**Comment by hejalsoni** [comment]
Attached is a picture of what it's showing me.

![screen shot 2015-02-23 at 10 25 40 am](https://cloud.githubusercontent.com/assets/10925312/6331701/6043e7dc-bb46-11e4-8121-d8d66c05ecef.png)
