### ISSUE TITLE
Telephone block does not allow any other characters other than integers

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#74]
For example, if a creator wants to use xxx-xxx-xxxx, it won't allow it to be submitted. Only xxxxxxxxxx can be inputted.

**Comment by tabrown3** [comment]
![screen shot 2015-02-23 at 10 50 39 am](https://cloud.githubusercontent.com/assets/7130820/6332410/ca570966-bb4a-11e4-8b22-8d05409f2549.png)

Works for Vu and me. Can you try it again and, if it still doesn't work, show me next time we're in the office at the same time? I can't reproduce.
