### ISSUE TITLE
default options (1.2)

### ISSUE THREAD

**Issue by DrDanPrice** [DataAnalyticsinStudentHands/FormBuilder#77]
for select, checkbox and radio, I think it would be fairly easy. 
Not sure how to do on Text input. Maybe a toggle next to placeholder that makes it default instead of placeholder that gets erased?

**Comment by DrDanPrice** [comment]
Use case is "Number of Guests" "0" should already be selected

**Comment by CarlSteven** [comment]
@tabrown3 is this ready to be merged in with default values for check and select boxes?

**Comment by tabrown3** [comment]
It is not ready to be merged, though it is very nearly complete.
