### ISSUE TITLE
File Upload functionality

### ISSUE THREAD

**Issue by peggylind** [DataAnalyticsinStudentHands/FormBuilder#8]

**Comment by CarlSteven** [comment]
Need server-side file upload functionality in separate table with owner/user + file URL information. We can then link to this in the response_entry as discussed.

**Comment by CarlSteven** [comment]
I am running into a "content type must be a valid javax.ws.rs.core.MediaType" error. Mostly copying from the $upload stuff in terryapp, so I must be making some mistake.

Can @Tswiggs shed some light on why I would get this?

**Comment by CarlSteven** [comment]
TerryApp's upload looks like:
public Response uploadFile(@QueryParam("id") Long id,
    @FormDataParam("file") InputStream uploadedInputStream,
    @FormDataParam("file") FormDataContentDisposition fileDetail,
    @HeaderParam("Content-Length") final long fileSize)
        throws AppException {
    ...

While FormBuilder's upload:
@Consumes({ MediaType.MULTIPART_FORM_DATA })
@Produces({ MediaType.TEXT_HTML })
public Response createFileUpload(@QueryParam("user_id") Long user_id,
    @QueryParam("form_id") Long form_id,
    @QueryParam("content_type") String content_type,
    @FormDataParam("file") InputStream uploadedInputStream,
    @FormDataParam("file") FormDataContentDisposition fileDetail,
    @HeaderParam("Content-Length") final long fileSize)
        throws AppException {
    ...

Why the need for the content_type query param? I have to set this manually.

**Comment by CarlSteven** [comment]
I think I figured it out to the extent needed for now.
