### ISSUE TITLE
@PUT to update a form is broken

### ISSUE THREAD

**Issue by srirampotluri** [DataAnalyticsinStudentHands/FormBuilder#82]
I have entered all the text boxes for the application and when i tried to save it, it didn't work. I tried refreshing and filling again but it didn't help saving.

Edit by tyler: This is a 500 error returned because of a primary key being duplicated probably in the Question table.

**Comment by Tswiggs** [comment]
Issue is cause by front end generating question_id for newly added questions which may cause a conflict if that key is in use by another form.
