### ISSUE TITLE
Form Builder Uneven Columns

### ISSUE THREAD

**Issue by CarlSteven** [DataAnalyticsinStudentHands/FormBuilder#90]
Just looks a tiny bit wonky on a large screen.

![image](https://cloud.githubusercontent.com/assets/7702743/6345214/fe25efa4-bbc8-11e4-8f58-dcf726299616.png)

**Comment by CarlSteven** [comment]
@nqv1994, could you please take a look at this?

**Comment by vnguyen9** [comment]
Done
