### ISSUE TITLE
Form Component Highlight vs. Drag

### ISSUE THREAD

**Issue by CarlSteven** [DataAnalyticsinStudentHands/FormBuilder#94]
Sometimes when trying to drag a component, it will highlight (select) it instead of drag.

**Comment by tabrown3** [comment]
Two HTML elements are covering that portion of the page. One is the form builder footer div, which can be removed from formbuilder.html if we want. The other is ng-notify.

![screen shot 2015-02-26 at 1 13 22 pm](https://cloud.githubusercontent.com/assets/7130820/6399631/4e4e70c2-bdb9-11e4-96a1-f7fa75192010.png)

ng-notify's z-index will only reduce to -999 after it has been called once. To fix this, we will need to go in to ng-notify and do what we've always done: give it a default z-index of -999. Thoughts?
