### ISSUE TITLE
Click here to close window doesn't work

### ISSUE THREAD

**Issue by peggylind** [DataAnalyticsinStudentHands/FormBuilder#97]
I tried to use the link to close the window and it didn't work.

Here is a copy of the error from the console:  "Scripts may close only the windows that were opened by it."

I used the Houston Reply form from our testing suite.
![screen shot 2015-02-24 at 8 10 07 am](https://cloud.githubusercontent.com/assets/6371988/6350909/f4754a48-bbfc-11e4-8198-d0f6385b4c72.png)

**Comment by CarlSteven** [comment]
Duplicate of #88 
There's no non-hacky way to do this for security reasons. Removing featuring.
